package job.bento;

import static org.junit.Assert.assertTrue;

import org.jsoup.nodes.Element;
import org.jsoup.parser.Tag;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import job.bento.utils.LinkUtils;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'bkalantzis' at '9/2/16 2:57 PM' with Gradle 2.13
 *
 * @author bkalantzis, @date 9/2/16 2:57 PM
 */
public class LinkUtilsTest {
	
    private Element wikiUrl;
    
    private Element wikiUrlAndLowerLink;

	private Element googleUrl;

	private Element wikiUrlAndUpperLink;

	private Element googleUrlAndLowerLink;

	private Element googleUrlAndUpperLink;
    
    private Element wikiPhilosophyLink;
    
    public class AnchorBuilder{
    	private String href = null;
    	private String innerHtml = null;
    	private Element clone = null;
    	
    	public Element build(){
    		Element el;
    		if(clone == null){
    			el = new Element(Tag.valueOf("a"), "");
    		}else{
    			el = clone;
    		}
    		
    		if(this.href != null){
    			el.attr("href", this.href);
    		}
    		
    		if(this.innerHtml != null){
    			el.html(this.innerHtml);
    		}
    		
    		return el;
    	}
    	
    	public AnchorBuilder withHref(String href){
    		this.href = href;
    		return this;
    	}
    	
    	public AnchorBuilder withInnerHtml(String innerHtml){
    		this.innerHtml = innerHtml;
    		return this;
    	}
    	
    	public AnchorBuilder modify(Element e){
    		this.clone = e.clone();
    		return this;
    	}
    }
    
    @Before public void setUp(){
    	this.wikiUrl = new AnchorBuilder()
    			.withHref("/wiki/test")
    			.build();
    	
    	this.wikiUrlAndLowerLink  = new AnchorBuilder()
    			.modify(wikiUrl)
    			.withInnerHtml("test")
    			.build();
    	
    	this.wikiUrlAndUpperLink = new AnchorBuilder()
    			.modify(wikiUrl)
    			.withInnerHtml("Test")
    			.build();
    	
    	this.googleUrl = new AnchorBuilder()
    			.withHref("http://www.google.com")
    			.build();
    	
    	this.googleUrlAndUpperLink = new AnchorBuilder()
    			.modify(googleUrl)
    			.withInnerHtml("Google")
    			.build();
    	
    	this.googleUrlAndLowerLink = new AnchorBuilder()
    			.modify(googleUrl)
    			.withInnerHtml("google")
    			.build();
    	
    	this.wikiPhilosophyLink = new AnchorBuilder()
    			.withHref("/wiki/Philosophy")
    			.withInnerHtml("Philosophy")
    			.build();
    }
    
    @Test public void testIsWikiHref(){
    	assertTrue(LinkUtils.isWikiHref(this.wikiUrl));
    }
    
    @Test public void testIsWikiInnerHtml(){
    	assertTrue(LinkUtils.isLowerCaseLink(this.wikiUrlAndLowerLink));
    }
    
    @Test public void testIsNotWikiInnerHtml(){
    	Assert.assertFalse(LinkUtils.isLowerCaseLink(this.wikiUrlAndUpperLink));
    }
    
    @Test public void testIsPhilosophyLink(){
    	assertTrue(LinkUtils.isPhilosophyLink(this.wikiPhilosophyLink));
    }
    
    @Test public void testIsNotPhilosophyLink(){
    	Assert.assertFalse(LinkUtils.isPhilosophyLink(this.googleUrlAndLowerLink));
    }
    
    @Test public void testIsCandidateLink(){
    	assertTrue(LinkUtils.isCandidateLink(this.wikiUrlAndLowerLink));
    }
    
}
